### ISSUE TITLE
Inverting brightness without changing hue.

### ISSUE THREAD

**Issue by StoneyEagle** [adamsonyanik/twitch-extension-color-inverter#1]
I come from purplelf's twitch stream.

I found a proper CSS filter that respects color.
I'm not sure if you like to add it as an option or want to make it the default so I'm just going to leave it here.

Base64 version:
```css
filter:url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/Pgo8IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPgo8c3ZnIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgPGRlZnM+ICAKICAgIDxmaWx0ZXIgaWQ9InZhbHVlX2ludmVydCIgY29sb3ItaW50ZXJwb2xhdGlvbi1maWx0ZXJzPSJzUkdCIj4KICAgICAgPGZlQ29sb3JNYXRyaXggcmVzdWx0PSJTb3VyY2VHcmFwaGljIiB0eXBlPSJzYXR1cmF0ZSIgdmFsdWVzPSIxIiAvPgogICAgICA8ZmVDb2xvck1hdHJpeCBpbj0iU291cmNlR3JhcGhpYyIgdmFsdWVzPSItMSAwIDAgMCAxIDAgLTEgMCAwIDEgMCAwIC0xIDAgMSAwIDAgMCAxIDAiIC8+CiAgICAgIDxmZUNvbG9yTWF0cml4IHR5cGU9Imh1ZVJvdGF0ZSIgdmFsdWVzPSIxODAiIC8+CiAgICA8L2ZpbHRlcj4KICA8L2RlZnM+Cjwvc3ZnPgo=#value_invert);
```

Regular SVG filter:
```css
 filter:url(#value_invert);
```
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
  <defs>  
    <filter id="value_invert" color-interpolation-filters="sRGB">
      <feColorMatrix result="SourceGraphic" type="saturate" values="1"/>
      <feColorMatrix in="SourceGraphic" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"/>
      <feColorMatrix type="hueRotate" values="180"/>
    </filter>
  </defs>
</svg>
```
The SVG just needs to exist on the DOM, doesn't matter where.

Purplelf asked if it's possible to add top and bottom cropping so the taskbar and the top overlay can be excluded.

Thanks.

**Comment by StoneyEagle** [comment]
Original:
![image](https://user-images.githubusercontent.com/45034970/160220191-8afe6d95-bcd3-49bc-988a-8a5a90d8d680.png)

This extension:
![image](https://user-images.githubusercontent.com/45034970/160220228-59affb75-907b-4f9a-a0a6-52b2c15bf14c.png)

My version:
![image](https://user-images.githubusercontent.com/45034970/160220240-c4ffc143-7ee1-43d2-a332-4b52ba17fea5.png)

Blue is still blue but darker and dark purple is still purple but lighter.

**Comment by adamsonyanik** [comment]
I added support for custom filters, streamers can set the css <tt>backdrop-filter</tt> property.
You could implement the that filter with: <tt>invert(100%) hue-rotate(180deg)</tt>

For the unmodified area I switched to the css property <tt>clip-path</tt>, so the top and bottom cropping shouldn't be a problem anymore.

**Comment by StoneyEagle** [comment]
Nice, how long does it usually take to see the changes in the extension?

**Comment by adamsonyanik** [comment]
v0.0.1 took one week to get approved.
